### ISSUE TITLE
Basic Commands

### ISSUE THREAD

**Issue by Zendrex** [Zendrex/vision-discordbot#1]
A list of commands and features to be added to VISION

## Commands
- [ ]  Help

### Fun
- [ ] CatFact
- [ ] ChuckNorris
- [ ] Insult

### Moderator
- [ ] Prune / Clear Chat

### Owner
- [ ] Reboot
- [ ] Reload 

### User
- [ ] Ask (8ball)
- [ ] BotStats
- [ ] Invite
- [ ] ServerInfo
- [ ] UserInfo

**Comment by Zendrex** [comment]
## Server Management Stuff
Each server should have specific settings to change things like prefix, roles, etc for the bot commands as well as the ability to enable/disable whichever command(s) they please.

### TODO
- [ ] Auto-Generate guild_settings database
- [ ] Check For DB Table Per-Server On Load
- [ ] Add a command to allow specific settings to be changed.
- [ ] Make it a web UI instead.
